# Lab Assignment 2: How to Load CSV, ASCII, and other data into Python
## DS 6001

100 points

### Instructions
Please answer the following questions as completely as possible using text, code, and the results of code as needed. Format your answers in a Jupyter notebook. To receive full credit, make sure you address every part of the problem, and make sure your document is formatted in a clean and professional way.

## Problem 1

There are several data files attached to this lab assignment, with different extensions. First, download all of these data files, and save them in the same folder on your local machine. Your task in the following questions is to load each file into Python correctly, so that you can begin the process of data cleaning. If the variable names are included in the file, use those names to name the columns. If the variable names are not included, use these names in order:

In [15]:
column_names = ["Country", "Happiness score", "Whisker-high", "Whisker-low", 
  "Dystopia (1.92) + residual", "Explained by: GDP per capita", 
  "Explained by: Social support", "Explained by: Healthy life expectancy", 
  "Explained by: Freedom to make life choices", "Explained by: Generosity", 
  "Explained by: Perceptions of corruption" ]

### Part a
Import the packages you will need. Then write code to change the working directory to the folder in which you saved the data files, run the code displayed above to create the `column_names` list, load `data_clean.csv`, and display the output of the `.info()` method of `data_clean`. [4 points]

In [16]:
import numpy as np
import pandas as pd
import os
import sys

In [17]:
sys.tracebacklimit = 0

In [18]:
oldpath = os.getcwd()
os.chdir(os.path.join(oldpath, "data"))

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:\\Users\\carlo\\Documents\\school\\uva-courses\\fall_26\\de\\ds6001-f26-qrk9cs\\ds6001-f26-qrk9cs\\lab_assignments\\lab_assignment2\\data\\data'

In [ ]:
df_data_clean = pd.read_csv("data_clean.csv")
df_data_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    str
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), str(1)
memory usage: 13.5 KB

In [ ]:
df_data_clean

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

### Part b
Load `data1.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [ ]:
df_data1 = pd.read_csv("data1.csv", header=2)
df_data1

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

For the dataset data1.csv, the way I decided on the right combination of parameters was by looking at the current DataFrame output. I noticed that the DataFrame was displaying two rows before the actual header, so I skipped those two rows by using header=2.

### Part c
Load `data2.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [6 points]

In [ ]:
df_data2 = pd.read_csv("data2.txt", header=2, comment="/")
df_data2

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

For data2.txt, I was having the same problem as with data1.csv. The only difference was that this dataset also had comments inside the data. I identified the first character used for these comments and used comment="/" to tell Python to ignore those rows.

### Part d
Load `data3.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [ ]:
df_data3 = pd.read_csv("data3.txt", sep="\t", header=2)
df_data3

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

For data3.txt, we were having the same problem with comments appearing before the column names as in the previous datasets, plus a new problem. Instead of using a comma "," as the delimiter, this file was using a tab "\t". So, I used sep="\t" to indicate that the delimiter for this dataset is a tab.

### Part e
Load `data4.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [ ]:
df_data4 = pd.read_csv("data4.txt", sep="$", names=column_names)
df_data4

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

For data4.txt, we were introduced to a new issue, the dataset was missing the header (column names). To fix this, I used the names parameter to assign the column names to the DataFrame.

### Part f
Load `data5.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [ ]:
df_data5 = pd.read_csv("data5.csv", skipfooter=2, engine="python")
df_data5

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

For data5.csv, the issue was that there were source links at the bottom of the file that were being displayed as rows in our dataset. To remove them, I used the skipfooter parameter to tell pandas to ignore the rows at the bottom of the file that contained the source links.

### Part g
Load `data6.dat`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (Note: for this question, your result won't look *exactly* like data_clean.csv, and that is OK.) [6 points]

In [ ]:
df_data6 = pd.read_csv("data6.dat", na_values = 999)
df_data6

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,NaN,NaN,NaN,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,NaN,NaN,1.582,NaN,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,NaN,0.683,0.284,0.408
3,Iceland,7.495,7.593,NaN,2.426,1.343,1.644,0.914,0.677,0.353,NaN
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,NaN,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,NaN,0.064
152,Tanzania,NaN,NaN,3.193,0.628,NaN,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,NaN,3.123,1.691,0.337,NaN,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,NaN,0.038
155,Burundi,2.905,3.074,NaN,1.752,0.091,NaN,0.145,0.065,0.149,0.076

For this dataset, I first thought I was going to read it using read_fwf(), but I noticed that the file was structured pretty much like a CSV file, with commas separating the values. So, I read it using read_csv(). The only issue I encountered was the missing values, which were represented as 999, so I addressed this by using the na_values parameter.

### Part h
Load `data7.xlsx`, which is an Excel file. Keep only the sheet named “Data”. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [27]:
df_data7 = pd.read_excel("data7.xlsx", sheet_name=[1])
df_data7[1]

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

For this dataset, I used a bit of trial and error. I knew that read_excel() could return the different sheets as DataFrames, so I first tried sheet 0. It returned data, but it was not the data we were looking for. I then tried the second sheet, sheet 1, and ended up getting the correct data.

### Part i
Load `data8.dta`, which is a Stata 13 file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [31]:
df_data8 = pd.read_stata("data8.dta")
df_data8.columns = column_names
df_data8

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

For this dataset, I think the only problem was with the header names. The data already had column names, but they were not displayed the way we wanted. To fix this, I replaced the current column names with the ones provided in column_names.

### Part j
Load `data9.sav`, which is an SPSS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

In [35]:
df_data9 = pd.read_spss("data9.sav")
df_data9.columns = column_names
df_data9

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

Similar to the previous problem, I replaced the header with more fitting column names. One thing to mention is that we are using a local file. As the reading mentions, the .sav format does not support loading data directly from a URL, so since our file is stored locally, I determined that using read_spss() was the appropriate option here.

### Part k
Load `data10.xpt`, which is a SAS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. 

(If some of the country names display as `b'Finland'`, don't worry about that.)

(But if you are still worrying about it ... issues like `b'Finland'` indicate a [character encoding](https://en.wikipedia.org/wiki/Character_encoding) issue, in which SAS uses a different encoding method than Python. In this case Python uses a default encoding called [UTF-8](https://en.wikipedia.org/wiki/UTF-8) and this SAS file has encoded characters using [Latin-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1). To get around this issue, add the `encoding='latin-1'` argument to your read method.) 

[4 points]

In [38]:
df_data10 = pd.read_sas("data10.xpt", encoding="latin-1")
df_data10.columns = column_names
df_data10

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592000e+00,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582000e+00,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590000e+00,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644000e+00,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549000e+00,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073000e+00,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,9.910000e-01,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,6.080000e-01,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,5.397605e-79,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,6.270000e-01,0.145,0.065,0.149,0.076

I used the recommended parameter encoding="latin-1" when reading the file so the country names would be displayed correctly.

### Part l
Please load the `data11.txt` file, which is a fixed width file. The columns are defined as follows:

| Variable                                   | Width | Start | End |
|--------------------------------------------|-------|-------|-----|
| Country                                    | 24    | 1     | 24  |
| Happiness score                            | 5     | 25    | 29  |
| Whisker-high                               | 5     | 30    | 34  |
| Whisker-low                                | 5     | 35    | 39  |
| Dystopia (1.92) + residual                 | 5     | 40    | 44  |
| Explained by: GDP per capita               | 5     | 45    | 49  |
| Explained by: Social support               | 5     | 50    | 54  |
| Explained by: Healthy life expectancy      | 5     | 55    | 59  |
| Explained by: Freedom to make life choices | 5     | 60    | 64  |
| Explained by: Generosity                   | 5     | 65    | 69  |
| Explained by: Perceptions of corruption    | 5     | 70    | 74  |

Then save the this loaded data frame as a CSV file on your local machine. Be sure to use a unique filename so as not to overwrite any existing files. [10 points]

In [40]:
datawidths = [24, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

df_data11 = pd.read_fwf("data11.txt", widths=datawidths, names=column_names)
df_data11

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

In [57]:
df_data11.to_csv("data11.csv", index=False)

data11.txt is a fixed-width file, and we were given both the widths and the start and end positions for each column. I decided to use the widths parameter to define the width of each column. Since the file was also missing the column names, I used the names parameter with the column_names list that was provided earlier.

## Problem 2
This problem walks through how to wrangle some difficult real-world Excel data into Python. This problem is guided, but later in the semester you'll be asked more often to do work with less guidance. 

The file named "epa_data.xlsx" contains data on the reproduction and growth of nine different plant species, measured once in 2010 and once in 2011. The data were compiled from the [EPA's repository](https://catalog.data.gov/dataset/18-excel-spreadsheets-by-species-and-year-giving-reproduction-and-growth-data-one-excel-sp) on data.gov. I placed all of the data into a single file, where the different species/year combinations are placed in different sheets. The file also includes a sheet for herbicide treatment chemistry data, and one sheet for a ReadMe describing some of the columns in the growth data.

### Part a
If you load an Excel file with multiple sheets into Python using the `sheet_name=None` argument, then every sheet's data will be stored in one big Python dictionary. 

We will discuss dictionaries (and JSON formatted data) in depth in module 3. However, for this problem, there a few points to know about dictionaries:

* Dictionaries are similar to lists, except that they are denoted with curly braces {} instead of square braces [], and that entries in the dictionary are indexed by names instead of numeric positions.

* Entries in a dictionary are called values, and the names attached to the entries are called keys. Your output will set the former sheet names as the keys for each data table.

* To display one of the values, call the Python variable that contains the dictionary, and index it by the value's key. For example, if you save the data as `epadata`, then you can see the 2010 data for species CALE by typing `epadata['CALE 2010']`. 

Load all of the data, across all of the sheets, from this Excel file into Python. Then index to one of the values in the resulting dictionary to display one of the former sheets as a pandas dataframe. [8 points]

In [45]:
epadata = pd.read_excel("epa_data.xlsx", sheet_name=None)
print(epadata.keys())

epadata["CALE 2010"]

dict_keys(['CALE 2010', 'CALE 2011', 'ELGL 2010', 'ELGL 2011', 'ERLA 2010', 'ERLA 2011', 'FEID 2010', 'FEID 2011', 'FRVI 2010', 'FRVI 2011', 'IRTE 2010', 'IRTE 2011', 'POGR 2010', 'POGR 2011', 'PRVU 2010', 'PRVU 2011', 'RAOC 2010', 'RAOC 2011', 'Solution Chemistry', 'ReadMe'])

,Year,Species,site,Plot,Trt,Treatment,pods,sqrtpods,cover0,arsincover0,...,arsincover3,matureseeds,logmatureseeddw,immatureseeddw,logimmatureseeddw,totalseeddw,logtotalseeddw,percentimmatureseed,arsinpercentimmatureseed,Final Comments
0,2010,CALE,Hyslop,4,6,Roundup 0.1,1.0,1.000000,1,0.100167,...,0.141897,0.0957,-1.019043,0.0000,-5.000000,0.0957,-1.019043,0.000000,0.000000,NaN
1,2010,CALE,Hyslop,12,7,Rdup/Bnvl 0.01,6.0,2.449490,2,0.141897,...,0.100167,0.3863,-0.413064,0.0041,-2.386158,0.3904,-0.408479,1.050205,0.102660,NaN
2,2010,CALE,Hyslop,13,5,Roundup 0.01,8.0,2.828427,2,0.141897,...,0.141897,0.2806,-0.551897,0.0031,-2.507240,0.2837,-0.547125,1.092704,0.104724,NaN
3,2010,CALE,Hyslop,15,1,Carrier Control,3.0,1.732051,1,0.100167,...,0.100167,0.0662,-1.179076,0.0001,-3.958607,0.0663,-1.178421,0.150830,0.038847,NaN
4,2010,CALE,Hyslop,17,3,Banvel 0.01,0.0,0.000000,1,0.100167,...,0.141897,0.0000,-5.000000,0.0000,-5.000000,0.0000,-5.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2010,CALE,Botany,382,8,Rdup/Bnvl 0.1,6.0,2.449490,1,0.100167,...,0.000000,0.0116,-1.935168,0.0020,-2.696804,0.0136,-1.866142,14.705882,0.393564,Died after harvest
124,2010,CALE,Botany,384,1,Carrier Control,NaN,NaN,1,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Cover 3 missing, missing at seed collection an..."
125,2010,CALE,Botany,388,3,Banvel 0.01,8.0,2.828427,2,0.141897,...,0.141897,0.4597,-0.337516,0.0004,-3.387216,0.4601,-0.337138,0.086938,0.029489,NaN
126,2010,CALE,Botany,399,8,Rdup/Bnvl 0.1,12.0,3.464102,1,0.100167,...,0.100167,0.2130,-0.671600,0.0068,-2.166853,0.2198,-0.657953,3.093722,0.176810,NaN
127,2010,CALE,Botany,400,2,No Spray,0.0,0.000000,1,0.100167,...,0.141897,0.0000,-5.000000,0.0000,-5.000000,0.0000,-5.000000,NaN,NaN,NaN

### Part b
To see all of the keys in the dictionary, use the `.keys()` method on the data dictionary you created in part a. If you do, you will notice that two keys are not like the others:

* `Solution Chemistry` contains different data: information about common pesticides instead of the growth and reproduction of a particular species of plant.

* `ReadMe` contains descriptions of some columns in the species-level data.

To delete a key and value from a dictionary, use the following syntax `del d[key]`, where `d` is the Python variable that contains the dictionary, and `key` is the name (quotes included) of the key attached to the value you want to remove from the dictionary. If you use this command, the dictionary is altered *in place*, meaning that there is no need to write `d=` before this command in order to make these edits to the dictionary permanent.

Delete the `Solution Chemistry` and `ReadMe` data from the dictionary. [8 points]

In [47]:
print(epadata.keys())

del epadata["Solution Chemistry"]
del epadata["ReadMe"]

print(epadata.keys())

dict_keys(['CALE 2010', 'CALE 2011', 'ELGL 2010', 'ELGL 2011', 'ERLA 2010', 'ERLA 2011', 'FEID 2010', 'FEID 2011', 'FRVI 2010', 'FRVI 2011', 'IRTE 2010', 'IRTE 2011', 'POGR 2010', 'POGR 2011', 'PRVU 2010', 'PRVU 2011', 'RAOC 2010', 'RAOC 2011', 'Solution Chemistry', 'ReadMe'])
dict_keys(['CALE 2010', 'CALE 2011', 'ELGL 2010', 'ELGL 2011', 'ERLA 2010', 'ERLA 2011', 'FEID 2010', 'FEID 2011', 'FRVI 2010', 'FRVI 2011', 'IRTE 2010', 'IRTE 2011', 'POGR 2010', 'POGR 2011', 'PRVU 2010', 'PRVU 2011', 'RAOC 2010', 'RAOC 2011'])

### Part c
Combining two data tables with the same columns but entirely different rows is called **appending** data. Our goal is to append all of the remaining data tables together, to create one large dataframe containing all plant species and both 2010 and 2011 data. 

It is only possible, however, to append data if both data tables have exactly the same column names. If a column in one table is not matched in the other table, the column will be populated with missing values for the rows that come from the second table. There are two reasons why columns might not match: the two tables might not contain the same features, or the two tables contain the same feature but named differently in each table. 

For example, in this case, some of the sheets have columns that others do not, such as biomass. Other features are present in every sheet, but with different names: year is sometimes spelled with a capital Y.

To deal with these issues, we will use a loop over the keys in the dictionary you edited in part b. Begin the loop by typing 
```
for df in d.keys():
```
where `d` is the name of your dictionary.

On the next line, indent (which indicates this line should be run within the loop). Then write
```
d[df].columns = d[df].columns.str.lower()
```
which will alter all column names across all of the dataframes to be lower-case.

In addition, some of the column names have extra spaces at the end, and that will make columns fail to match as well. To remove these spaces, add the following line to the loop:

```
d[df].columns = d[df].columns.str.strip()
```
which removes leading and trailing spaces from each column name. [10 points]

In [49]:
for df in epadata.keys():
    epadata[df].columns = epadata[df].columns.str.lower()
    epadata[df].columns = epadata[df].columns.str.strip()

### Part d
Use the `pd.concat()` method to append all of the dataframes in your dictionary together. You can pass the entire dictionary to the first argument of `pd.concat()`. Specify `ignore_index=True`, which resets the row numbering instead of bringing in the old row numbers from the individual dataframes. [8 points]

In [53]:
epadata =pd.concat(epadata, ignore_index=True)
epadata

,year,species,site,plot,trt,treatment,pods,sqrtpods,cover0,arsincover0,...,totseeddw,infloroescences,sqrtinfluorescences,atypicalinfluorescences,sqrtatypicalinfluorescences,totalinflorescence,sqrttotalinfluorescences,percentatypical,arsinpercentatypical,treatment #
0,2010,CALE,Hyslop,4,6,Roundup 0.1,1.0,1.000000,1.0,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,CALE,Hyslop,12,7,Rdup/Bnvl 0.01,6.0,2.449490,2.0,0.141897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,CALE,Hyslop,13,5,Roundup 0.01,8.0,2.828427,2.0,0.141897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,CALE,Hyslop,15,1,Carrier Control,3.0,1.732051,1.0,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,CALE,Hyslop,17,3,Banvel 0.01,0.0,0.000000,1.0,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2299,2011,RAOC,Botany,370,8,Rdup+Bnvl 0.2,NaN,NaN,0.2,0.044736,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2300,2011,RAOC,Botany,377,3,Banvel 0.1,NaN,NaN,0.5,0.070770,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
2301,2011,RAOC,Botany,379,4,Banvel 0.2,NaN,NaN,0.3,0.054800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
2302,2011,RAOC,Botany,380,2,No Spray,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2303,2011,RAOC,Botany,382,4,Banvel 0.2,NaN,NaN,0.2,0.044736,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0

### Part e
Many of the features that were brought into the appended dataframe were only present for one or a small number of the dataframes. Keep only the following features, which are present for most of the species:

In [54]:
cols_to_keep = ['year', 'species', 'site', 'plot', 'trt', 'treatment', 
                'pods', 'cover0', 'arsincover0', 'cover3', 'arsincover3', 
                'cover5', 'arsincover5']

Then save the resulting data in a separate CSV file. [8 points]

In [56]:
epadata = epadata[cols_to_keep]
epadata

epadata.to_csv("epa_clean.csv", index=False)