In [1]:
import numpy as np
import pandas as pd
import requests # handles HTTP requests
import json # handles JSON data

In [2]:
url = 'https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=Cocktail'

In [4]:
r = requests.get(url)
r

In [ ]:
r.text

'{"drinks":[{"strDrink":"155 Belmont","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/yqvvqs1475667388.jpg","idDrink":"15346"},{"strDrink":"57 Chevy with a White License Plate","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/qyyvtu1468878544.jpg","idDrink":"14029"},{"strDrink":"747 Drink","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/i9suxb1582474926.jpg","idDrink":"178318"},{"strDrink":"9 1\\/2 Weeks","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/xvwusr1472669302.jpg","idDrink":"16108"},{"strDrink":"A Gilligan\'s Island","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/wysqut1461867176.jpg","idDrink":"16943"},{"strDrink":"A True Amaretto Sour","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/rptuxy1472669372.jpg","idDrink":"17005"},{"strDrink":"A.D.M. (After Dinner Mint)","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/ruxuvp1472669600.jpg","idDrink":"14560"},{"strDrink":"A1","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/2x8thr1504816928.jpg","idDrink":"17222"},{"strDrink":"Abbey Martini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/2mcozt1504817403.jpg","idDrink":"17223"},{"strDrink":"Absolut Summertime","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/trpxxs1472669662.jpg","idDrink":"14107"},{"strDrink":"Absolutely Fabulous","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/abcpwr1504817734.jpg","idDrink":"17224"},{"strDrink":"Absolutly Screwed Up","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/yvxrwv1472669728.jpg","idDrink":"16134"},{"strDrink":"Ace","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/l3cd7f1504818306.jpg","idDrink":"17225"},{"strDrink":"Adam & Eve","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/vfeumw1504819077.jpg","idDrink":"17226"},{"strDrink":"Addington","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/ib0b7g1504818925.jpg","idDrink":"17227"},{"strDrink":"Addison","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/yzva7x1504820300.jpg","idDrink":"17228"},{"strDrink":"Addison Special","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/4vo5651493068493.jpg","idDrink":"14272"},{"strDrink":"Adios Amigos Cocktail","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/8nk2mp1504819893.jpg","idDrink":"17229"},{"strDrink":"Afterglow","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/vuquyv1468876052.jpg","idDrink":"12560"},{"strDrink":"Alice Cocktail","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/qyqtpv1468876144.jpg","idDrink":"12562"},{"strDrink":"Amaretto fizz","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/92h3jz1582474310.jpg","idDrink":"178321"},{"strDrink":"Aperol Spritz","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/iloasq1587661955.jpg","idDrink":"178325"},{"strDrink":"Apple Highball","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/66mt9b1619695719.jpg","idDrink":"178353"},{"strDrink":"Applejack","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/sutyqp1479209062.jpg","idDrink":"16311"},{"strDrink":"Aquamarine","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/zvsre31572902738.jpg","idDrink":"178319"},{"strDrink":"Arizona Stingers","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/y7w0721493068255.jpg","idDrink":"14584"},{"strDrink":"Arizona Twister","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/ido1j01493068134.jpg","idDrink":"17074"},{"strDrink":"Army special","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/55muhh1493068062.jpg","idDrink":"17066"},{"strDrink":"Autumn Garibaldi","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/ne7re71604179012.jpg","idDrink":"178337"},{"strDrink":"Aviation","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/trbplb1606855233.jpg","idDrink":"17180"},{"strDrink":"Bahama Mama","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/tyb4a41515793339.jpg","idDrink":"17267"},{"strDrink":"Banana Cream Pi","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/m5p67n1582474609.jpg","idDrink":"178320"},{"strDrink":"Bee\'s Knees","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/tx8ne41582475326.jpg","idDrink":"178317"},{"strDrink":"Bijou","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/rysb3r1513706985.jpg","idDrink":"17254"},{"strDrink":"Blue Hurricane","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/nwx02s1515795822.jpg","idDrink":"17268"},{"strDrink":"Blueberry Mojito","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/07iep51598719977.jpg","idDrink":"178336"},{"strDrink":"Bombay Cassis","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/h1e0e51510136907.jpg","idDrink":"17242"},{"strDrink":"Bora Bora","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/xwuqvw1473201811.jpg","idDrink":"12572"},{"strDrink":"Boulevardier","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/km84qi1513705868.jpg","idDrink":"17251"},{"strDrink":"Bounty Hunter","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/t8bgxl1596018175.jpg","idDrink":"178331"},{"strDrink":"Brigadier","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/nl89tf1518947401.jpg","idDrink":"17825"},{"strDrink":"Broadside","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/l2o6xu1582476870.jpg","idDrink":"178311"},{"strDrink":"Brooklyn","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/ojsezf1582477277.jpg","idDrink":"178310"},{"strDrink":"Butterfly Effect","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/ht3hnk1619704289.jpg","idDrink":"178356"},{"strDrink":"Captain Kidd\'s Punch","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/d83spj1596017390.jpg","idDrink":"178329"},{"strDrink":"Cherry Electric Lemonade","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/tquyyt1451299548.jpg","idDrink":"17174"},{"strDrink":"Cocktail Horse\\u2019s Neck","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/4vobt21643844913.jpg","idDrink":"178369"},{"strDrink":"Corn n Oil","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/pk6dwi1592767243.jpg","idDrink":"17830"},{"strDrink":"Corpse Reviver","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/gifgao1513704334.jpg","idDrink":"17250"},{"strDrink":"Cosmopolitan","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/kpsajh1504368362.jpg","idDrink":"17196"},{"strDrink":"Cosmopolitan Martini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/upxxpq1439907580.jpg","idDrink":"14133"},{"strDrink":"Cream Soda","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/yqstxr1479209367.jpg","idDrink":"14608"},{"strDrink":"Dark Caipirinha","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/uwstrx1472406058.jpg","idDrink":"17177"},{"strDrink":"Death in the Afternoon","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/y7s3rh1598719574.jpg","idDrink":"178334"},{"strDrink":"Dirty Martini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/vcyvpq1485083300.jpg","idDrink":"17181"},{"strDrink":"Dry Martini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/6ck9yi1589574317.jpg","idDrink":"11005"},{"strDrink":"Duchamp\'s Punch","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/g51naw1485084685.jpg","idDrink":"17182"},{"strDrink":"Elderflower Caipirinha","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/dif7a31614006331.jpg","idDrink":"178346"},{"strDrink":"Empell\\u00f3n Cocina\'s Fat-Washed Mezcal","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/osgvxt1513595509.jpg","idDrink":"17246"},{"strDrink":"Espresso Martini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/n0sx531504372951.jpg","idDrink":"17212"},{"strDrink":"Espresso Rumtini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/acvf171561574403.jpg","idDrink":"178309"},{"strDrink":"Figgy Thyme","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/pbw4e51606766578.jpg","idDrink":"178344"},{"strDrink":"Flaming Lamborghini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/yywpss1461866587.jpg","idDrink":"16485"},{"strDrink":"French Martini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/clth721504373134.jpg","idDrink":"17213"},{"strDrink":"French Negroni","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/x8lhp41513703167.jpg","idDrink":"17248"},{"strDrink":"Fros\\u00e9","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/b4cadp1619695347.jpg","idDrink":"178352"},{"strDrink":"Funk and Soul","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/qtv83q1596015790.jpg","idDrink":"178328"},{"strDrink":"Gagliardo","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/lyloe91487602877.jpg","idDrink":"12758"},{"strDrink":"Garibaldi Negroni","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/kb4bjg1604179771.jpg","idDrink":"178340"},{"strDrink":"Gimlet","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/3xgldt1513707271.jpg","idDrink":"17255"},{"strDrink":"Gin and Soda","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/nzlyc81605905755.jpg","idDrink":"178342"},{"strDrink":"Gin Basil Smash","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/jqh2141572807327.jpg","idDrink":"178314"},{"strDrink":"Gin Lemon","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/6gdohq1681212476.jpg","idDrink":"178366"},{"strDrink":"Gin Rickey","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/s00d6f1504883945.jpg","idDrink":"17230"},{"strDrink":"Gin Tonic","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/qcgz0t1643821443.jpg","idDrink":"178365"},{"strDrink":"Greyhound","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/g5upn41513706732.jpg","idDrink":"17252"},{"strDrink":"Honey Bee","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/vu8l7t1582475673.jpg","idDrink":"178316"},{"strDrink":"Hot Toddy","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/ggx0lv1613942306.jpg","idDrink":"178345"},{"strDrink":"Hunter\'s Moon","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/t0iugg1509556712.jpg","idDrink":"17239"},{"strDrink":"Imperial Cocktail","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/bcsj2e1487603625.jpg","idDrink":"12706"},{"strDrink":"Irish Curdling Cow","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/yrhutv1503563730.jpg","idDrink":"16987"},{"strDrink":"Jitterbug","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/wwqvrq1441245318.jpg","idDrink":"16178"},{"strDrink":"Kiwi Martini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/bmxmyq1630407098.jpg","idDrink":"178359"},{"strDrink":"Lazy Coconut Paloma","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/rytuex1598719770.jpg","idDrink":"178335"},{"strDrink":"Lemon Drop","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/mtpxgk1504373297.jpg","idDrink":"14366"},{"strDrink":"Lemon Elderflower Spritzer","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/125w0o1630407389.jpg","idDrink":"178360"},{"strDrink":"Malibu Twister","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/2dwae41504885321.jpg","idDrink":"15224"},{"strDrink":"Mango Mojito","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/wfqmgm1630406820.jpg","idDrink":"178358"},{"strDrink":"Manhattan","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/yk70e31606771240.jpg","idDrink":"11008"},{"strDrink":"Martinez 2","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/fs6kiq1513708455.jpg","idDrink":"17256"},{"strDrink":"Martinez Cocktail","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/wwxwvr1439906452.jpg","idDrink":"11720"},{"strDrink":"Martini","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/71t8581504353095.jpg","idDrink":"11728"},{"strDrink":"Mary Pickford","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/f9erqb1504350557.jpg","idDrink":"17188"},{"strDrink":"Mauresque","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/duwfa11686236556.jpg","idDrink":"178370"},{"strDrink":"Miami Vice","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/qvuyqw1441208955.jpg","idDrink":"13936"},{"strDrink":"Michelada","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/u736bd1605907086.jpg","idDrink":"178343"},{"strDrink":"Midnight Mint","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/svuvrq1441208310.jpg","idDrink":"14842"},{"strDrink":"Mojito","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/metwgh1606770327.jpg","idDrink":"11000"},{"strDrink":"Mojito Extra","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/vwxrsw1478251483.jpg","idDrink":"15841"},{"strDrink":"Mountain Bramble","strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/stwiva1619704025.jpg","idDrink":"178355"}]}'

In [11]:
#r.json()
myjson = json.loads(r.text)
myjson

{'drinks': [{'strDrink': '155 Belmont',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yqvvqs1475667388.jpg',
   'idDrink': '15346'},
  {'strDrink': '57 Chevy with a White License Plate',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qyyvtu1468878544.jpg',
   'idDrink': '14029'},
  {'strDrink': '747 Drink',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/i9suxb1582474926.jpg',
   'idDrink': '178318'},
  {'strDrink': '9 1/2 Weeks',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xvwusr1472669302.jpg',
   'idDrink': '16108'},
  {'strDrink': "A Gilligan's Island",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wysqut1461867176.jpg',
   'idDrink': '16943'},
  {'strDrink': 'A True Amaretto Sour',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rptuxy1472669372.jpg',
   'idDrink': '17005'},
  {'strDrink': 'A.D.M. (After Dinner Mint)',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ruxuvp1472669600.jpg',
   'idDrink': '14560'},
  {'strDrink': 'A1',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
   'idDrink': '17222'},
  {'strDrink': 'Abbey Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2mcozt1504817403.jpg',
   'idDrink': '17223'},
  {'strDrink': 'Absolut Summertime',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/trpxxs1472669662.jpg',
   'idDrink': '14107'},
  {'strDrink': 'Absolutely Fabulous',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/abcpwr1504817734.jpg',
   'idDrink': '17224'},
  {'strDrink': 'Absolutly Screwed Up',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yvxrwv1472669728.jpg',
   'idDrink': '16134'},
  {'strDrink': 'Ace',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
   'idDrink': '17225'},
  {'strDrink': 'Adam & Eve',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vfeumw1504819077.jpg',
   'idDrink': '17226'},
  {'strDrink': 'Addington',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ib0b7g1504818925.jpg',
   'idDrink': '17227'},
  {'strDrink': 'Addison',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yzva7x1504820300.jpg',
   'idDrink': '17228'},
  {'strDrink': 'Addison Special',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/4vo5651493068493.jpg',
   'idDrink': '14272'},
  {'strDrink': 'Adios Amigos Cocktail',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/8nk2mp1504819893.jpg',
   'idDrink': '17229'},
  {'strDrink': 'Afterglow',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vuquyv1468876052.jpg',
   'idDrink': '12560'},
  {'strDrink': 'Alice Cocktail',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qyqtpv1468876144.jpg',
   'idDrink': '12562'},
  {'strDrink': 'Amaretto fizz',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/92h3jz1582474310.jpg',
   'idDrink': '178321'},
  {'strDrink': 'Aperol Spritz',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/iloasq1587661955.jpg',
   'idDrink': '178325'},
  {'strDrink': 'Apple Highball',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/66mt9b1619695719.jpg',
   'idDrink': '178353'},
  {'strDrink': 'Applejack',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/sutyqp1479209062.jpg',
   'idDrink': '16311'},
  {'strDrink': 'Aquamarine',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg',
   'idDrink': '178319'},
  {'strDrink': 'Arizona Stingers',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/y7w0721493068255.jpg',
   'idDrink': '14584'},
  {'strDrink': 'Arizona Twister',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ido1j01493068134.jpg',
   'idDrink': '17074'},
  {'strDrink': 'Army special',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/55muhh1493068062.jpg',
   'idDrink': '17066'},
  {'strDrink': 'Autumn Garibaldi',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ne7re71604179012.jpg',
   'idDrink': '178337'},
  {'strDrink': 'Aviation',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/trbplb1606855233.jpg',
   'idDrink': '17180'},
  {'strDrink': 'Bahama Mama',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tyb4a41515793339.jpg',
   'idDrink': '17267'},
  {'strDrink': 'Banana Cream Pi',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/m5p67n1582474609.jpg',
   'idDrink': '178320'},
  {'strDrink': "Bee's Knees",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tx8ne41582475326.jpg',
   'idDrink': '178317'},
  {'strDrink': 'Bijou',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg',
   'idDrink': '17254'},
  {'strDrink': 'Blue Hurricane',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/nwx02s1515795822.jpg',
   'idDrink': '17268'},
  {'strDrink': 'Blueberry Mojito',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/07iep51598719977.jpg',
   'idDrink': '178336'},
  {'strDrink': 'Bombay Cassis',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/h1e0e51510136907.jpg',
   'idDrink': '17242'},
  {'strDrink': 'Bora Bora',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/xwuqvw1473201811.jpg',
   'idDrink': '12572'},
  {'strDrink': 'Boulevardier',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/km84qi1513705868.jpg',
   'idDrink': '17251'},
  {'strDrink': 'Bounty Hunter',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/t8bgxl1596018175.jpg',
   'idDrink': '178331'},
  {'strDrink': 'Brigadier',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/nl89tf1518947401.jpg',
   'idDrink': '17825'},
  {'strDrink': 'Broadside',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/l2o6xu1582476870.jpg',
   'idDrink': '178311'},
  {'strDrink': 'Brooklyn',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ojsezf1582477277.jpg',
   'idDrink': '178310'},
  {'strDrink': 'Butterfly Effect',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ht3hnk1619704289.jpg',
   'idDrink': '178356'},
  {'strDrink': "Captain Kidd's Punch",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/d83spj1596017390.jpg',
   'idDrink': '178329'},
  {'strDrink': 'Cherry Electric Lemonade',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tquyyt1451299548.jpg',
   'idDrink': '17174'},
  {'strDrink': 'Cocktail Horse’s Neck',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/4vobt21643844913.jpg',
   'idDrink': '178369'},
  {'strDrink': 'Corn n Oil',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pk6dwi1592767243.jpg',
   'idDrink': '17830'},
  {'strDrink': 'Corpse Reviver',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/gifgao1513704334.jpg',
   'idDrink': '17250'},
  {'strDrink': 'Cosmopolitan',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg',
   'idDrink': '17196'},
  {'strDrink': 'Cosmopolitan Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/upxxpq1439907580.jpg',
   'idDrink': '14133'},
  {'strDrink': 'Cream Soda',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yqstxr1479209367.jpg',
   'idDrink': '14608'},
  {'strDrink': 'Dark Caipirinha',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/uwstrx1472406058.jpg',
   'idDrink': '17177'},
  {'strDrink': 'Death in the Afternoon',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/y7s3rh1598719574.jpg',
   'idDrink': '178334'},
  {'strDrink': 'Dirty Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vcyvpq1485083300.jpg',
   'idDrink': '17181'},
  {'strDrink': 'Dry Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg',
   'idDrink': '11005'},
  {'strDrink': "Duchamp's Punch",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/g51naw1485084685.jpg',
   'idDrink': '17182'},
  {'strDrink': 'Elderflower Caipirinha',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/dif7a31614006331.jpg',
   'idDrink': '178346'},
  {'strDrink': "Empellón Cocina's Fat-Washed Mezcal",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/osgvxt1513595509.jpg',
   'idDrink': '17246'},
  {'strDrink': 'Espresso Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/n0sx531504372951.jpg',
   'idDrink': '17212'},
  {'strDrink': 'Espresso Rumtini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/acvf171561574403.jpg',
   'idDrink': '178309'},
  {'strDrink': 'Figgy Thyme',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/pbw4e51606766578.jpg',
   'idDrink': '178344'},
  {'strDrink': 'Flaming Lamborghini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yywpss1461866587.jpg',
   'idDrink': '16485'},
  {'strDrink': 'French Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/clth721504373134.jpg',
   'idDrink': '17213'},
  {'strDrink': 'French Negroni',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/x8lhp41513703167.jpg',
   'idDrink': '17248'},
  {'strDrink': 'Frosé',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/b4cadp1619695347.jpg',
   'idDrink': '178352'},
  {'strDrink': 'Funk and Soul',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qtv83q1596015790.jpg',
   'idDrink': '178328'},
  {'strDrink': 'Gagliardo',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/lyloe91487602877.jpg',
   'idDrink': '12758'},
  {'strDrink': 'Garibaldi Negroni',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/kb4bjg1604179771.jpg',
   'idDrink': '178340'},
  {'strDrink': 'Gimlet',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/3xgldt1513707271.jpg',
   'idDrink': '17255'},
  {'strDrink': 'Gin and Soda',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/nzlyc81605905755.jpg',
   'idDrink': '178342'},
  {'strDrink': 'Gin Basil Smash',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/jqh2141572807327.jpg',
   'idDrink': '178314'},
  {'strDrink': 'Gin Lemon',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/6gdohq1681212476.jpg',
   'idDrink': '178366'},
  {'strDrink': 'Gin Rickey',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/s00d6f1504883945.jpg',
   'idDrink': '17230'},
  {'strDrink': 'Gin Tonic',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qcgz0t1643821443.jpg',
   'idDrink': '178365'},
  {'strDrink': 'Greyhound',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/g5upn41513706732.jpg',
   'idDrink': '17252'},
  {'strDrink': 'Honey Bee',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vu8l7t1582475673.jpg',
   'idDrink': '178316'},
  {'strDrink': 'Hot Toddy',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/ggx0lv1613942306.jpg',
   'idDrink': '178345'},
  {'strDrink': "Hunter's Moon",
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/t0iugg1509556712.jpg',
   'idDrink': '17239'},
  {'strDrink': 'Imperial Cocktail',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/bcsj2e1487603625.jpg',
   'idDrink': '12706'},
  {'strDrink': 'Irish Curdling Cow',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yrhutv1503563730.jpg',
   'idDrink': '16987'},
  {'strDrink': 'Jitterbug',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wwqvrq1441245318.jpg',
   'idDrink': '16178'},
  {'strDrink': 'Kiwi Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/bmxmyq1630407098.jpg',
   'idDrink': '178359'},
  {'strDrink': 'Lazy Coconut Paloma',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/rytuex1598719770.jpg',
   'idDrink': '178335'},
  {'strDrink': 'Lemon Drop',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/mtpxgk1504373297.jpg',
   'idDrink': '14366'},
  {'strDrink': 'Lemon Elderflower Spritzer',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/125w0o1630407389.jpg',
   'idDrink': '178360'},
  {'strDrink': 'Malibu Twister',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/2dwae41504885321.jpg',
   'idDrink': '15224'},
  {'strDrink': 'Mango Mojito',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wfqmgm1630406820.jpg',
   'idDrink': '178358'},
  {'strDrink': 'Manhattan',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/yk70e31606771240.jpg',
   'idDrink': '11008'},
  {'strDrink': 'Martinez 2',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/fs6kiq1513708455.jpg',
   'idDrink': '17256'},
  {'strDrink': 'Martinez Cocktail',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/wwxwvr1439906452.jpg',
   'idDrink': '11720'},
  {'strDrink': 'Martini',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/71t8581504353095.jpg',
   'idDrink': '11728'},
  {'strDrink': 'Mary Pickford',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/f9erqb1504350557.jpg',
   'idDrink': '17188'},
  {'strDrink': 'Mauresque',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/duwfa11686236556.jpg',
   'idDrink': '178370'},
  {'strDrink': 'Miami Vice',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/qvuyqw1441208955.jpg',
   'idDrink': '13936'},
  {'strDrink': 'Michelada',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/u736bd1605907086.jpg',
   'idDrink': '178343'},
  {'strDrink': 'Midnight Mint',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/svuvrq1441208310.jpg',
   'idDrink': '14842'},
  {'strDrink': 'Mojito',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg',
   'idDrink': '11000'},
  {'strDrink': 'Mojito Extra',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vwxrsw1478251483.jpg',
   'idDrink': '15841'},
  {'strDrink': 'Mountain Bramble',
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/stwiva1619704025.jpg',
   'idDrink': '178355'}]}

In [12]:
myjson['drinks'][0]['strDrink']

'155 Belmont'

**List comprehension:** a loop over item in a list, outputs results to a different list.

In [13]:
[x['strDrink'] for x in myjson['drinks']]

['155 Belmont',
 '57 Chevy with a White License Plate',
 '747 Drink',
 '9 1/2 Weeks',
 "A Gilligan's Island",
 'A True Amaretto Sour',
 'A.D.M. (After Dinner Mint)',
 'A1',
 'Abbey Martini',
 'Absolut Summertime',
 'Absolutely Fabulous',
 'Absolutly Screwed Up',
 'Ace',
 'Adam & Eve',
 'Addington',
 'Addison',
 'Addison Special',
 'Adios Amigos Cocktail',
 'Afterglow',
 'Alice Cocktail',
 'Amaretto fizz',
 'Aperol Spritz',
 'Apple Highball',
 'Applejack',
 'Aquamarine',
 'Arizona Stingers',
 'Arizona Twister',
 'Army special',
 'Autumn Garibaldi',
 'Aviation',
 'Bahama Mama',
 'Banana Cream Pi',
 "Bee's Knees",
 'Bijou',
 'Blue Hurricane',
 'Blueberry Mojito',
 'Bombay Cassis',
 'Bora Bora',
 'Boulevardier',
 'Bounty Hunter',
 'Brigadier',
 'Broadside',
 'Brooklyn',
 'Butterfly Effect',
 "Captain Kidd's Punch",
 'Cherry Electric Lemonade',
 'Cocktail Horse’s Neck',
 'Corn n Oil',
 'Corpse Reviver',
 'Cosmopolitan',
 'Cosmopolitan Martini',
 'Cream Soda',
 'Dark Caipirinha',
 'Death in the Afternoon',
 'Dirty Martini',
 'Dry Martini',
 "Duchamp's Punch",
 'Elderflower Caipirinha',
 "Empellón Cocina's Fat-Washed Mezcal",
 'Espresso Martini',
 'Espresso Rumtini',
 'Figgy Thyme',
 'Flaming Lamborghini',
 'French Martini',
 'French Negroni',
 'Frosé',
 'Funk and Soul',
 'Gagliardo',
 'Garibaldi Negroni',
 'Gimlet',
 'Gin and Soda',
 'Gin Basil Smash',
 'Gin Lemon',
 'Gin Rickey',
 'Gin Tonic',
 'Greyhound',
 'Honey Bee',
 'Hot Toddy',
 "Hunter's Moon",
 'Imperial Cocktail',
 'Irish Curdling Cow',
 'Jitterbug',
 'Kiwi Martini',
 'Lazy Coconut Paloma',
 'Lemon Drop',
 'Lemon Elderflower Spritzer',
 'Malibu Twister',
 'Mango Mojito',
 'Manhattan',
 'Martinez 2',
 'Martinez Cocktail',
 'Martini',
 'Mary Pickford',
 'Mauresque',
 'Miami Vice',
 'Michelada',
 'Midnight Mint',
 'Mojito',
 'Mojito Extra',
 'Mountain Bramble']

Record path, the path to a list of rows in the data frame I am trying to build

In this case, the record path is just: 'drinks'

In [14]:
drinksDF = pd.json_normalize(myjson, record_path=['drinks'])
drinksDF

,strDrink,strDrinkThumb,idDrink
0,155 Belmont,https://www.thecocktaildb.com/images/media/dri...,15346
1,57 Chevy with a White License Plate,https://www.thecocktaildb.com/images/media/dri...,14029
2,747 Drink,https://www.thecocktaildb.com/images/media/dri...,178318
3,9 1/2 Weeks,https://www.thecocktaildb.com/images/media/dri...,16108
4,A Gilligan's Island,https://www.thecocktaildb.com/images/media/dri...,16943
...,...,...,...
95,Michelada,https://www.thecocktaildb.com/images/media/dri...,178343
96,Midnight Mint,https://www.thecocktaildb.com/images/media/dri...,14842
97,Mojito,https://www.thecocktaildb.com/images/media/dri...,11000
98,Mojito Extra,https://www.thecocktaildb.com/images/media/dri...,15841
99,Mountain Bramble,https://www.thecocktaildb.com/images/media/dri...,178355

In [16]:
botname = 'ds6001'
version = '0.0'
website = 'https://virginia.edu'
email = 'jkropko@virginia.edu'


useragent = f'{botname}/{version} ({website}; {email}) python-requests/{requests.__version__}'
useragent

'ds6001/0.0 (https://virginia.edu; jkropko@virginia.edu) python-requests/2.34.2'

In [17]:
headers = {'User-Agent': useragent}
headers

{'User-Agent': 'ds6001/0.0 (https://virginia.edu; jkropko@virginia.edu) python-requests/2.34.2'}

In [ ]:
url = 'https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Virginia&format=json&srlimit=500'
r = requests.get(url, headers=headers)
myjson = r.json()

In [22]:
wikiDF = pd.json_normalize(myjson, record_path=['query', 'search'])
wikiDF

,ns,title,pageid,size,wordcount,snippet,timestamp
0,0,Virginia,32432,294898,25256,"<span class=""searchmatch"">Virginia</span>, off...",2026-09-04T16:06:13Z
1,0,West Virginia,32905,187865,18238,"West <span class=""searchmatch"">Virginia</span>...",2026-09-04T11:10:19Z
2,0,"Virginia Beach, Virginia",91239,138322,12433,"<span class=""searchmatch"">Virginia</span> Beac...",2026-08-22T11:09:58Z
3,0,Virginia Woolf,32742,161730,16600,"Adeline <span class=""searchmatch"">Virginia</sp...",2026-09-03T11:15:03Z
4,0,Government of Virginia,14316834,17305,1904,"of <span class=""searchmatch"">Virginia</span> c...",2026-03-03T18:41:59Z
...,...,...,...,...,...,...,...
495,0,"Paynesville, Virginia",26201975,2424,46,"County, <span class=""searchmatch"">Virginia</sp...",2026-07-26T18:01:42Z
496,0,Kingsport–Bristol–Bristol metropolitan area,1533383,13319,599,metropolitan statistical area (MSA) in Northea...,2026-08-14T19:19:25Z
497,0,Virginia Demetricia,64479501,9003,790,"<span class=""searchmatch"">Virginia</span> Deme...",2026-02-28T19:58:41Z
498,0,"McDowell County, West Virginia",91031,46297,3855,McDowell County is a county in the State of We...,2026-09-04T16:06:13Z
499,0,Virginia State Route 25,6367452,286,66,"in <span class=""searchmatch"">Virginia</span> h...",2015-12-27T18:11:25Z

# DO NOT THIS!
## DON'T PASTE AN APIKEY INTO YOUR CODE. USE A .ENV FILE INSTEAD (MODULE 4)

In [23]:
apikey = '6f98fcb09b664cdaafae9c1f62456b16'

In [25]:
url = 'https://newsapi.org/v2/everything'
params = {'apiKey': apikey, 
              'q': 'soup'}

r = requests.get(url, params=params, headers=headers)
r.json()

{'status': 'ok',
 'totalResults': 1111,
 'articles': [{'source': {'id': 'business-insider',
    'name': 'Business Insider'},
   'author': 'Erin McDowell',
   'title': "I made the easy sausage and tortellini soup I've been seeing online. It's perfect for busy weeknights.",
   'description': 'The easy sausage and tortellini soup recipe was hearty, but unbelievably easy to make.',
   'url': 'https://www.businessinsider.com/sausage-and-tortellini-soup-recipe-how-to-make-photos#article',
   'urlToImage': 'https://i.insider.com/6a8715677e0482203ed17fcc?width=1200&format=jpeg',
   'publishedAt': '2026-08-22T15:30:01Z',
   'content': "The easy sausage and tortellini soup recipe was hearty, but unbelievably easy to make.Erin McDowell/Business Insider\r\n<ul><li>As fall approaches, I've been seeing recipes for sausage and tortellini s… [+7003 chars]"},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Vanessa Imus',
   'title': "As a dietitian, here's how I turn Costco's $5 rotisserie chicken into a week of easy, well-balanced meals for my family",
   'description': "As a dietitian, here's how I'd make a week of easy meals for my family using $5 rotisserie chicken from Costco, from soup recipes to no-cook dinners.",
   'url': 'https://www.businessinsider.com/week-of-meals-using-rotisserie-chicken-costco-dietitian-recipes-2026-9#article',
   'urlToImage': 'https://i.insider.com/6a95d17d3f7df8787cff5895?width=1200&format=jpeg',
   'publishedAt': '2026-09-01T15:02:01Z',
   'content': "One $5 rotisserie chicken from Costco can easily be turned into a variety of different dinners and lunches.Vanessa Imus\r\n<ul><li>As a dietitian, here's how I turn a $5 Costco rotisserie chicken into … [+4825 chars]"},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Matthew Phelan',
   'title': 'Scientists Identify Mushroom That Makes You Hallucinate ‘Tiny People’',
   'description': 'Mycologists have identified a species of mushroom that induces hallucinations of dozens and sometimes hundreds of tiny people. The fungi is native to China and the Philippines.',
   'url': 'https://gizmodo.com/scientists-identify-mushroom-that-makes-you-hallucinate-tiny-people-2000798367',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/08/mushroom-Lanmaoa-asiatica-tiny-people-hallucinations-1200x675.jpg',
   'publishedAt': '2026-08-13T18:45:19Z',
   'content': 'Indigenous traditions across North America, Celtic folklore across the British Isles, and frankly cultures practically everywhere else in the worldfrom the West African nation of Senegal to China to … [+4280 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Anneta Konstantinides',
   'title': 'I got the chance to speak to Dolly Parton, and she was full of great life lessons. These are my favorites.',
   'description': 'Dolly Parton died on Tuesday at the age of 80. I had the chance to interview the country music icon, and she shared many great life lessons.',
   'url': 'https://www.businessinsider.com/dolly-parton-best-life-lessons-advice-2026-8#article',
   'urlToImage': 'https://i.insider.com/6a8e55f679f11f0a89f90bde?width=1200&format=jpeg',
   'publishedAt': '2026-08-26T16:03:03Z',
   'content': 'Dolly Parton taught us so many life lessons.Paul Natkin/Getty Images\r\n<ul><li>Dolly Parton died on Tuesday. She was 80 years old.</li><li>I had the chance to interview Parton, and she was full of gre… [+7684 chars]'},
  {'source': {'id': None, 'name': 'Skinnytaste.com'},
   'author': 'Gina Homolka',
   'title': 'Stracciatella Soup with Spinach and Orzo',
   'description': 'Stracciatella soup is a cozy Italian egg drop soup made with rich chicken broth and Parmesan. I add orzo and fresh spinach to make it a satisfying meal. Done in just 20 minutes! Easy Stracciatella Soup Recipe If you’ve never had stracciatella soup before, it’…',
   'url': 'https://www.skinnytaste.com/spinach-stracciatella-soup-with-orzo/',
   'urlToImage': 'https://www.skinnytaste.com/wp-content/uploads/2009/11/Stracciatella-Soup-17.jpg',
   'publishedAt': '2026-08-11T14:28:55Z',
   'content': "hi! i actually just found your site today and am very, very excited about making some of your recipes! but i have a dumb (read: newbie) question. i've ordered a food scale with ounces but, 'til it ar… [+372 chars]"},
  {'source': {'id': 'buzzfeed', 'name': 'Buzzfeed'},
   'author': 'Sara Thompson',
   'title': 'The Soup Of The Day Is "ADEMNSY" — Can You Unscramble Your Way To The Very End?',
   'description': 'How many words can you make from A, D, E, M, N, S, and Y?View Entire Post ›',
   'url': 'https://www.buzzfeed.com/sarathompson1/soup-of-the-day-september-5-2026',
   'urlToImage': 'https://img.buzzfeed.com/buzzfeed-static/static/2026-09/04/13/thumb/sToK-DNI5.jpg?crop=2999:1570;0,2%26downsize=1250:*',
   'publishedAt': '2026-09-05T10:16:03Z',
   'content': 'How many words can you make from A, D, E, M, N, S, and Y?'},
  {'source': {'id': 'buzzfeed', 'name': 'Buzzfeed'},
   'author': 'Sara Thompson',
   'title': 'The Soup Of The Day Is "EGILOW" — Can Your Brain Solve All The Words?',
   'description': 'How many words can you make from E, G, I, L, O, and W?View Entire Post ›',
   'url': 'https://www.buzzfeed.com/sarathompson1/soup-of-the-day-august-17-2026',
   'urlToImage': 'https://img.buzzfeed.com/buzzfeed-static/static/2026-08/14/16/thumb/7nCFhSeZF.jpg?crop=2999:1570;0,2%26downsize=1250:*',
   'publishedAt': '2026-08-17T10:16:04Z',
   'content': 'How many words can you make from E, G, I, L, O, and W?'},
  {'source': {'id': 'buzzfeed', 'name': 'Buzzfeed'},
   'author': 'Sara Thompson',
   'title': 'The Soup Of The Day Is "AELMPS" — Can Your Brain Knit Alllllll The Words Together?',
   'description': 'How many words can you make from A, E, L, M, P, and S?View Entire Post ›',
   'url': 'https://www.buzzfeed.com/sarathompson1/soup-of-the-day-august-13-2026',
   'urlToImage': 'https://img.buzzfeed.com/buzzfeed-static/static/2026-08/12/19/thumb/f6FI39DUg.jpg?crop=2999:1570;0,2%26downsize=1250:*',
   'publishedAt': '2026-08-13T10:16:04Z',
   'content': 'How many words can you make from A, E, L, M, P, and S?'},
  {'source': {'id': 'buzzfeed', 'name': 'Buzzfeed'},
   'author': 'Sara Thompson',
   'title': 'The Soup Of The Day Is “AEILNST” — How Many Words Can Your Brain Compute Together?',
   'description': 'How many words can you make from A, E, I, L, N, S, and T?View Entire Post ›',
   'url': 'https://www.buzzfeed.com/sarathompson1/soup-of-the-day-august-8-2026',
   'urlToImage': 'https://img.buzzfeed.com/buzzfeed-static/static/2026-08/07/16/thumb/sVwR6nHZw.jpg?crop=2999:1570;0,2%26downsize=1250:*',
   'publishedAt': '2026-08-08T10:16:02Z',
   'content': 'How many words can you make from A, E, I, L, N, S, and T?'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Trent Pheifer',
   'title': "I've cooked well over 1,000 Ina Garten recipes. Here are 10 of my favorites for an easy dinner.",
   'description': "I've spent years making all of Ina Garten's recipes. Here are the chef's best recipes for quick, easy dinners that come together in under an hour.",
   'url': 'https://www.businessinsider.com/best-dinner-recipes-ina-garten-suggestions-cooked-them-all-2026-9#article',
   'urlToImage': 'https://i.insider.com/6a95d97f79f11f0a89f92e2f?width=1200&format=jpeg',
   'publishedAt': '2026-09-01T13:30:18Z',
   'content': "I've spent years making many of Ina Garten's dinner recipes, and I have a few favorites for when I want an easy meal.Trent Pheifer\r\n<ul><li>I've spent years cooking all of celebrity chef Ina Garten's… [+5915 chars]"},
  {'source': {'id': None, 'name': 'CNET'},
   'author': 'Anna Gragert',
   'title': 'Before Splurging on a $500 Vitamix, Consider This Cheaper Model. It Works Just as Well',
   'description': 'If you’re in the market for a Vitamix blender, you don’t need to shell out $500 to get the best model.',
   'url': 'https://www.cnet.com/home/kitchen-and-household/before-splurging-on-a-500-vitamix-consider-this-cheaper-model-it-works-just-as-well/',
   'urlToImage': 'https://www.cnet.com/wp-content/uploads/sites/2/vitamix-vx1.png',
   'publishedAt': '2026-08-25T04:50:52Z',
   'content': '<ul><li>If you want a great Vitamix blender, you dont have to spend $500 for a great model. Go for the VX1 instead and save yourself $120.</li><li>The VX1 has self-cleaning and pulse modes, a sleek, … [+4845 chars]'},
  {'source': {'id': None, 'name': 'Mental Floss'},
   'author': 'Jenny Cohen',
   'title': 'The Most Popular Soup in Every State, Mapped',
   'description': 'Discover the most popular soup in every U.S. state, based on data analyzing regional preferences from matzah ball to French onion.',
   'url': 'https://www.mentalfloss.com/geography/maps/most-popular-soup-by-state-map',
   'urlToImage': 'https://images2.minutemediacdn.com/image/upload/c_crop,x_0,y_393,w_1400,h_787/c_fill,w_1440,ar_1440:810,f_auto,q_auto,g_auto/images/voltaxMediaLibrary/mmsport/mentalfloss/01m1davbbfkgqdr8q5py.jpg',
   'publishedAt': '2026-09-02T18:00:00Z',
   'content': 'Cooler weather calls for warm ideas for lunch and dinner, and one super option is soup.\r\nA good bowl of soup might be packed with veggies or noodles or chickenor all three depending on your favorite … [+4312 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Erin McDowell',
   'title': "I tried Chili's crispy chicken sandwich, which is driving sales. It showed me why the chain is winning the value wars.",
   'description': "Chili's said its crispy chicken sandwich is boosting sales. I tried the sandwich to see why it's become such a hit for the chain.",
   'url': 'https://www.businessinsider.com/chilis-crispy-chicken-sandwich-review-value-2026-8#article',
   'urlToImage': 'https://i.insider.com/6a7de7adc78818eff7d2ca27?width=1200&format=jpeg',
   'publishedAt': '2026-08-13T17:32:26Z',
   'content': "I tried Chili's crispy chicken sandwich, which the chain credited with boosting sales.Erin McDowell/Business Insider\r\n<ul><li>Chili's just released its latest earnings and credited its chicken sandwi… [+3595 chars]"},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Melia Robinson',
   'title': 'Google is taking on Anthropic and OpenAI in the legal AI race',
   'description': 'Google unveils Gemini Enterprise for Legal, targeting law firms with AI tools like agents for contract review and regulatory tracking.',
   'url': 'https://www.businessinsider.com/google-unveils-gemini-enterprise-for-legal-law-tech-push-2026-8#article',
   'urlToImage': 'https://i.insider.com/6a8d9d4545e6f385a51687f2?width=1200&format=jpeg',
   'publishedAt': '2026-08-25T15:06:31Z',
   'content': 'Gemini is entering the legal tech space.Thomas Trutschel/Photothek via Getty Images\r\n<ul><li>Google has joined the fray of enterprise software giants building software specifically for lawyers.</li><… [+2727 chars]'},
  {'source': {'id': None, 'name': 'Github.io'},
   'author': None,
   'title': 'Salad Theory',
   'description': 'Salad Theory',
   'url': 'https://saladtheory.github.io/',
   'urlToImage': None,
   'publishedAt': '2026-08-31T03:11:39Z',
   'content': 'Background\r\nIn our office, we sometimes enjoy pedantic conversations where we attempt to properly define ambiguous terms. Naturally, when the sandwich controversy took the world by storm around 2016[… [+21093 chars]'},
  {'source': {'id': None, 'name': 'Boing Boing'},
   'author': 'Gareth Branwyn',
   'title': 'A Ghost Arm Made of Angry Ghosts mixes DC punk with dead superheroes',
   'description': "I'm looking forward to reading A Ghost Arm Made of Angry Ghosts, the new graphic novel from writer/colorist Oliver Mertz and artist Alex Diotto. And not just because that is one hell of a killer title.\nThe book is set in the Washington, DC punk scene of the 1…",
   'url': 'https://boingboing.net/2026/09/01/a-ghost-arm-made-of-angry-ghosts-mixes-dc-punk-with-dead-sup.html',
   'urlToImage': 'https://i0.wp.com/boingboing.net/wp-content/uploads/2026/09/GHOST-ARM-COVER-UPDATED-copy.jpeg?fit=1200%2C676&quality=60&ssl=1',
   'publishedAt': '2026-09-01T15:42:51Z',
   'content': "I'm looking forward to reading A Ghost Arm Made of Angry Ghosts, the new graphic novel from writer/colorist Oliver Mertz and artist Alex Diotto. And not just because that is one hell of a killer titl… [+2233 chars]"},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Jason Guerrasio',
   'title': '12 celebrities who support AI',
   'description': 'Major Hollywood players like James Cameron and Ben Affleck have put their chips in the ever-expanding world of artificial intelligence.',
   'url': 'https://www.businessinsider.com/pro-ai-celebrities-investors-companies#article',
   'urlToImage': 'https://i.insider.com/6a85e46c85cca0a87cd8aae8?width=1200&format=jpeg',
   'publishedAt': '2026-08-21T20:30:19Z',
   'content': 'Ben Affleck, Natasha Lyonne, and James Cameron.Getty\r\n<ul><li>The use of artificial intelligence is dividing Hollywood.</li><li>Some people are against it for creative endeavors, and are protecting t… [+10404 chars]'},
  {'source': {'id': None, 'name': 'Hackaday'},
   'author': 'Tyler August',
   'title': 'Have Scientists Stuck the Landing on the Glueball Discovery?',
   'description': 'Exciting discoveries in particle physics are one of those things that it can be easy to get blase about. Some people get caught up in the obvious excitement, while others yawn: “Oh, you found…',
   'url': 'https://hackaday.com/2026/08/12/have-scientists-stuck-the-landing-on-the-glueball-discovery/',
   'urlToImage': 'https://hackaday.com/wp-content/uploads/2026/08/BesIII-feat.jpg',
   'publishedAt': '2026-08-13T02:00:57Z',
   'content': 'Exciting discoveries in particle physics are one of those things that it can be easy to get blase about. Some people get caught up in the obvious excitement, while others yawn: “Oh, you found the Hig… [+2651 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'insider@insider.com (Jackie Fishman)',
   'title': 'At 69, we traded our empty-nester condo in the city for a much larger house in the suburbs',
   'description': "Once we had grandkids, my husband and I left our condo for a larger suburban home. At first, we worried we wouldn't fit in with our younger neighbors.",
   'url': 'https://www.businessinsider.com/moved-from-city-to-suburb-late-60s-made-younger-friends-2026-8#article',
   'urlToImage': 'https://i.insider.com/6a832def4aad6e24b69bad01?width=1200&format=jpeg',
   'publishedAt': '2026-08-19T13:36:36Z',
   'content': 'When my husband and I first became empty nesters more than 20 years ago, we moved from our suburban Maryland home to a two-bedroom condo in Arlington, Virginia. We hoped to make some new friends as w… [+3712 chars]'},
  {'source': {'id': None, 'name': 'Cheezburger.com'},
   'author': 'Sarah Brown , Sarah Brown',
   'title': 'Smol Soup Belly Babies Filling Their Tummies and Cat Pawrents’ Hearts',
   'description': 'Nothing says "dinner was a success" quite like a cat waddling away from the bowl with a freshly filled soup belly.\r\nSoup belly season is always in full swing when there are hungry felines around. One minute, you\'ve got a perfectly normal-shaped cat yelling fo…',
   'url': 'https://cheezburger.com/46404613/smol-soup-belly-babies-filling-their-tummies-and-cat-pawrents-hearts',
   'urlToImage': 'https://i.chzbgr.com/original/46404613/h2776F283/28-cat-pictures-thumbnail-includes-two-pictures-of-cats',
   'publishedAt': '2026-08-12T13:30:00Z',
   'content': "Soup belly season is always in full swing when there are hungry felines around. One minute, you've got a perfectly normal-shaped cat yelling for dinner. A few noms later, you're looking at a suspicio… [+1297 chars]"},
  {'source': {'id': None, 'name': 'Thekitchn.com'},
   'author': 'Micki Wagner',
   'title': 'Is East Fork Worth It? Everything to Know About the Fan-Favorite Pottery',
   'description': 'For a long time, I had a mishmash of tableware in my cabinets: old ceramic plates from my parents, a cheap plastic bowl and plate set I bought from Amazon, a soup bowl I got free from a work giveaway. My cabinets finally looked a little more pulled together w…',
   'url': 'https://www.thekitchn.com/is-east-fork-worth-it-23840533',
   'urlToImage': 'https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/shopping%2Ftk%2F2026%2F2026-08%2Feast-fork-brand-explainer%2Feast-fork-lead',
   'publishedAt': '2026-08-28T16:45:00Z',
   'content': 'We independently select these products—if you buy from one of our links, we may earn a commission. All prices were accurate at the time of publishing.\r\nFor a long time, I had a mishmash of tableware … [+5892 chars]'},
  {'source': {'id': None, 'name': 'Kotaku'},
   'author': 'Rebekah Valentine',
   'title': '13 Fields of Mistria Tips For First-Time Farmers',
   'description': 'Starting your first farm in Mistria 1.0? Here are a few things that will make your journey easier',
   'url': 'https://kotaku.com/13-fields-of-mistria-tips-for-first-time-farmers-2000723128',
   'urlToImage': 'https://kotaku.com/app/uploads/2026/08/fields-of-mistria-trailer-1.jpg',
   'publishedAt': '2026-08-10T22:45:34Z',
   'content': 'Last week, I started Fields of Mistria, a game my friends have been raving about for ages while it was in early access, but which just now entered its full, 1.0 launch. And man, my friends were right… [+7690 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'Kelly Burch',
   'title': "I'm a doctor who tracks my health. My 93-year-old dad does none of that.",
   'description': 'Dr. Jessica Wu, 58, says her 93-year-old dad skips gyms and supplements. His simple longevity habits have changed how she practices medicine.',
   'url': 'https://www.businessinsider.com/healthy-aging-longevity-habits-no-gym-2026-8#article',
   'urlToImage': 'https://i.insider.com/6a8861ea1d1a1d028ba11a75?width=1080&format=jpeg',
   'publishedAt': '2026-08-21T14:46:14Z',
   'content': "Dr. Wu's father is 93 and still dances the ballroom.Courtesy of Dr. Wu\r\n<ul><li>Dr. Jessica Wu is a dermatologist who trained at Harvard Medical School.</li><li>Her dad, 93, incorporates movement int… [+3759 chars]"},
  {'source': {'id': None, 'name': 'Slickdeals.net'},
   'author': 'SUCHaDEAL',
   'title': "16oz. Rao's Made For Home Slow Simmered Soup (Chicken Noodle) $3.20 w/ S&S",
   'description': "Amazon has 16oz. Rao's Made For Home Slow Simmered Soup (Chicken Noodle) on sale for $3.97 - 5% ($0.20) Subscribe & Save - Extra 15% Off ($0.60) coupon found on product page = $3.17. Shipping",
   'url': 'https://slickdeals.net/f/19862055-16oz-rao-s-made-for-home-slow-simmered-soup-chicken-noodle-3-20-w-s-s',
   'urlToImage': 'https://slickdeals.net/attachment/8/6/6/3/0/450x450/21250995.thumb',
   'publishedAt': '2026-08-11T11:32:46Z',
   'content': 'This collaborative space allows users to contribute additional information, tips, and insights to enhance the original deal post. Feel free to share your knowledge and help fellow shoppers make infor… [+26 chars]'},
  {'source': {'id': None, 'name': 'Slickdeals.net'},
   'author': 'hocuspocusblade',
   'title': 'Select Accts: 22-Pk 3-oz Maruchan Ramen Fire Noodle Soup (Spicy Beef) $9.45 w/ S&S',
   'description': 'Amazon has for Select Accounts:\xa022-Pack 3-Oz Maruchan Ramen Fire Noodle Soup (Spicy Beef, 100262) for $10.99 - $1 off when you clip the coupon on the product page - 5% off when you checkout via Subsc',
   'url': 'https://slickdeals.net/f/19867140-maruchan-ramen-noodle-soup-fire-spicy-beef-flavor-japanese-style-instant-noodles-quick-easy-meal-3-oz-22-pack-9-44-after-coupon-s-s-amazon',
   'urlToImage': 'https://slickdeals.net/attachment/1/7/2/9/6/9/0/450x450/21253212.thumb',